main.py
#impor do flask
from flask import Flask
from routes.home import home_route
from routes.cliente import cliente_route

#Inicializando Flask
app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')

#Executando Flask
app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES

cliente_route = Blueprint('cliente', __name__)

@cliente_route.route('/')
def lista_clientes():
    """ Tela inicial que lista clientes"""
    return render_template('lista_clientes.html', clientes=CLIENTES)

@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    """ Inserir os dados do cliente no banco de dados"""

    data = request.json

    novo_usuario = {
        "id": len(CLIENTES) + 1,
        "nome": data['nome'],
        "email": data['email'],
    }

    CLIENTES.append(novo_usuario)
    return render_template('item_cliente.html', cliente=novo_usuario)
    

@cliente_route.route('/new')
def form_cliente():
    """ Tela para criar novo cliente"""
    return render_template('form_cliente.html')

@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    """ Exibir detalhes do cliente """
    return render_template('detalhe_cliente.html')

@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    """ Formulario para editar o cliente """
    pass

@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_cliente(cliente_id):
    """ Atualizar informações do cliente """
    return render_template('form_edit_cliente.html')

@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):
    """ Deletar informações do cliente """
    pass

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/form_cliente.html
<form class="c-form" action="{{ url.for('cliente.inserir_cliente') }}" method="POST">

  <div class="mb-3">
    <label class="form-label">Nome: </label>
    <input type="text" class="form-control" name="nome">
  </div>

  <div class="mb-3">
    <label class="form-label">Email: </label>
    <input type="text" class="form-control" name="email">
  </div>

  <button type="submit" class="btn btn-primary">Criar cliente</button>
</form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
  </head>
  <body>

  <div class="container"> 
    <h1 class="text-center"> Gestão de Clientes </h1>

    <!-- Formulário add clientes -->
    <div c-container="{{ url_for('cliente.form_cliente') }}"></div>
    <hr>

    <!-- Listar clientes -->
    <div c-container="{{ url_for('cliente.lista_clientes') }}"></div>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='cru.js') }}"></script>
  </body>
</html>

templates/item.cliente.html
        <tr>
        <th scope="row">{{ cliente.id }}</th>
        <td>{{ cliente.name }}</td>
        <td>{{ cliente.email }}</td>
        <td>
            <button class="btn btn-primary">Editar</button>
            <button class="btn btn-primary">Deletar</button>
        </td>
        </tr>

templates/lista_clientes.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>

    {% for cliente in clientes %}
        {% include 'item_cliente.html' %}
    {% endfor %}
  </tbody>
</table>